// Test route for Sentry server-side error reporting, tracing, and logging (development/testing only)
// Visit /api/test-sentry-server to trigger various Sentry server features

import { NextResponse } from "next/server"
import * as Sentry from "@sentry/nextjs"

export async function GET() {
  // Only allow in development or with explicit test parameter
  if (process.env.NODE_ENV === "production" && !process.env.ALLOW_SENTRY_TEST) {
    return NextResponse.json(
      { error: "Test route disabled in production" },
      { status: 403 }
    )
  }

  return Sentry.startSpan(
    {
      op: "http.server",
      name: "GET /api/test-sentry-server",
    },
    async (span) => {
      // Add attributes to the span
      span.setAttribute("test", true)
      span.setAttribute("source", "test-server-route")
      span.setAttribute("runtime", "server")
      span.setAttribute("nodeVersion", process.version)

      const { logger } = Sentry

      try {
        // Test 1: Logger examples for server-side
        logger.info("Starting Sentry server test route", {
          route: "/api/test-sentry-server",
          nodeVersion: process.version,
        })
        logger.debug(logger.fmt`Server test route called at ${new Date().toISOString()}`)

        // Test 2: Trace a simulated database query
        const userData = await Sentry.startSpan(
          {
            op: "db.query",
            name: "SELECT user FROM users",
          },
          async (dbSpan) => {
            dbSpan.setAttribute("db.system", "postgresql")
            dbSpan.setAttribute("db.operation", "select")
            dbSpan.setAttribute("db.table", "users")
            dbSpan.setAttribute("simulated", true)

            // Simulate database query time
            await new Promise((resolve) => setTimeout(resolve, 150))

            logger.debug("Simulated database query completed", {
              duration: 150,
              operation: "select",
            })

            return { id: 1, name: "Test User" }
          }
        )

        // Test 3: Trace an HTTP client call (simulated)
        await Sentry.startSpan(
          {
            op: "http.client",
            name: "GET /api/external-service",
          },
          async (httpSpan) => {
            httpSpan.setAttribute("http.method", "GET")
            httpSpan.setAttribute("http.url", "/api/external-service")
            httpSpan.setAttribute("simulated", true)

            await new Promise((resolve) => setTimeout(resolve, 200))

            logger.info("Simulated external API call completed", {
              duration: 200,
              endpoint: "/api/external-service",
            })
          }
        )

        logger.warn("Simulated warning for testing", {
          endpoint: "/api/test-sentry-server",
          isEnterprise: false,
        })

        // Test 4: Simulate a server-side error
        throw new Error(
          "Test Sentry server error - This is intentional for server-side testing!"
        )
      } catch (error) {
        // Test 5: Capture server-side error with context
        Sentry.captureException(error, {
          tags: {
            test: true,
            source: "test-server-route",
            runtime: "server",
          },
          extra: {
            testMessage: "This server error was generated by the test route",
            timestamp: new Date().toISOString(),
            nodeVersion: process.version,
          },
          level: "error",
        })

        // Log the error with logger
        logger.error("Test server error occurred", {
          errorMessage: error instanceof Error ? error.message : String(error),
          route: "/api/test-sentry-server",
          nodeVersion: process.version,
        })

        return NextResponse.json(
          {
            success: true,
            message: "Test server error sent to Sentry!",
            error: error instanceof Error ? error.message : String(error),
            sentryConfigured:
              !!process.env.SENTRY_DSN || !!process.env.NEXT_PUBLIC_SENTRY_DSN,
            note: "Check your Sentry dashboard to see this server error, trace, and logs",
          },
          { status: 200 }
        )
      }
    }
  )
}
