// Test route for Sentry error reporting, tracing, and logging (development/testing only)
// Visit /api/test-sentry to trigger various Sentry features

import { NextResponse } from "next/server"
import * as Sentry from "@sentry/nextjs"

export async function GET() {
  // Only allow in development or with explicit test parameter
  if (process.env.NODE_ENV === "production" && !process.env.ALLOW_SENTRY_TEST) {
    return NextResponse.json(
      { error: "Test route disabled in production" },
      { status: 403 }
    )
  }

  return Sentry.startSpan(
    {
      op: "http.server",
      name: "GET /api/test-sentry",
    },
    async (span) => {
      // Add attributes to the span
      span.setAttribute("test", true)
      span.setAttribute("source", "test-route")

      try {
        // Test 1: Logger examples
        const { logger } = Sentry
        logger.info("Starting Sentry test route", { route: "/api/test-sentry" })
        logger.debug(logger.fmt`Test route called at ${new Date().toISOString()}`)
        
        // Test 2: Trace a simulated operation with a child span
        await Sentry.startSpan(
          {
            op: "function",
            name: "Simulate API Call",
          },
          async (childSpan) => {
            childSpan.setAttribute("operation", "fetch_user_data")
            childSpan.setAttribute("simulated", true)
            
            // Simulate some work
            await new Promise((resolve) => setTimeout(resolve, 100))
            
            // Use logger within span
            logger.debug("Simulated API call completed", { duration: 100 })
          }
        )

        // Test 3: Throw an error (will be auto-captured)
        throw new Error("Test Sentry error - This is intentional for testing!")

        // This won't execute, but included for type safety
        return NextResponse.json({ success: true })
      } catch (error) {
        // Test 4: Manual exception capture with context
        Sentry.captureException(error, {
          tags: {
            test: true,
            source: "test-route",
          },
          extra: {
            testMessage: "This error was generated by the test route",
            timestamp: new Date().toISOString(),
          },
          level: "error",
        })

        // Log the error
        const { logger } = Sentry
        logger.error("Test error occurred", {
          errorMessage: error instanceof Error ? error.message : String(error),
          route: "/api/test-sentry",
        })

        // Return response so we can see the test was triggered
        return NextResponse.json(
          {
            success: true,
            message: "Test error sent to Sentry!",
            error: error instanceof Error ? error.message : String(error),
            sentryConfigured: !!process.env.NEXT_PUBLIC_SENTRY_DSN,
            note: "Check your Sentry dashboard to see this error, trace, and logs",
          },
          { status: 200 }
        )
      }
    }
  )
}
